### ISSUE TITLE
Resource manager

### ISSUE THREAD

**Issue by JaimieVos** [Wase-Engine/wase-engine#111]
**Describe the solution you'd like**
A resource manager that loads and keeps track of all resources such as images and audio files in an efficiënt way.

**Comment by Crawfish-h** [comment]
I am very close to being done with playing audio files.

**Comment by Crawfish-h** [comment]
I am finished with the sound and I am adding the resource manager.

**Comment by JaimieVos** [comment]
> The comment above me was wrong at the time. I am finished with the sound and I am adding the resource manager.
@Crawfish-h cool! How are you making the sounds, which library are you using? The reason why I didn't have an issue on audio yet is because it will be quite a complex system in it's entirety so I am very curious about how your approach is

**Comment by Crawfish-h** [comment]
> > The comment above me was wrong at the time. I am finished with the sound and I am adding the resource manager.
> 
> @Crawfish-h cool! How are you making the sounds, which library are you using? The reason why I didn't have an issue on audio yet is because it will be quite a complex system in it's entirety so I am very curious about how your approach is

I am using the openal library. I have created a class that handles the device and context, a class that handles the buffer, and a class the handles the source.

How would you like me to create the resource manager? I feel like there is a big chance I will create something you may not like.

**Comment by JaimieVos** [comment]
> > > The comment above me was wrong at the time. I am finished with the sound and I am adding the resource manager.
> > 
> > 
> > @Crawfish-h cool! How are you making the sounds, which library are you using? The reason why I didn't have an issue on audio yet is because it will be quite a complex system in it's entirety so I am very curious about how your approach is
> 
> I am using openal and sndfile. I have created a class that handles the device and context, a class that handles the buffer, and a class the handles the source.
> 
> How would you like me to create the resource manager? I feel like there is a big chance I will create something you may not like.

I really do not know it yet, it is something I didn't research fully yet on how I would implement it. The best for now if you are working on the audio is I think is just to make it without a resource manager.
