### ISSUE TITLE
IO writing methods

### ISSUE THREAD

**Issue by JaimieVos** [Wase-Engine/wase-engine#125]
**Describe the solution you'd like**
A namespace that contains methods to write information to the filesystem

- [x] copy: copies the source path to the target path
- [x] remove: deletes a file/folder
- [x] createFile: creates a file at the target location
- [x] createFolder: creates a folder at the target location
- [x] write: write to the target file

**Comment by Crawfish-h** [comment]
could you be more specific on what you want the methods to do?

**Comment by JaimieVos** [comment]
> could you be more specific on what you want the methods to do?

@Crawfish-h I am currently working on some rendering and I am planning to push that really soon. For that I've made a very small beginning for the IO. When I am done with that and pushed it I will think out the specific methods the io namespace should contain and update this issue. Expect this to be within 24 hours / tomorrow.

**Comment by JaimieVos** [comment]
@Crawfish-h I updated the issue, also updated issue #124
