### ISSUE TITLE
in engine.cpp the at line 122 "m_SceneManager->addScenes(m_Config.scenes);" does not add a scene to the m_Config variable.

### ISSUE THREAD

**Issue by Crawfish-h** [Wase-Engine/wase-engine#128]
**Describe the bug**
In the file "engine.cpp" at line 122 in the function "bool Engine::initializeSceneManager()" the line of code "m_SceneManager->addScenes(m_Config.scenes);" does not add a scene object to "m_Config.scenes".

**To Reproduce**
start wase-engine

**Expected behavior**
A window should appear when I start wase-engine

**System information:**
 - OS: Ubuntu
 - Version: 22.04

**Additional context**
I was able to run wase-engine before input was added but I don't think the bug has anything to do with input.

**Comment by JaimieVos** [comment]
This is not a bug. I haven't updated the documentation yet in the [documentation repository](https://github.com/Wase-Engine/wase-engine-docs) yet but this is a priority of mine so things like this will be more clear. The way the Configuration struct is used is as following:
```c++
#include <unordered_map>
#include <string>

#include <engine.h>
#include <scene/scene.h>
#include <system/configuration.h>

#include <scenes/main_scene.h>
#include <scenes/second_scene.h>

int main()
{
    std::unordered_map<std::string, std::shared_ptr<wase::scene::Scene>> scenes =
    {
        { "main", std::make_shared<MainScene>() },
	{ "second", std::make_shared<SecondScene>() }
    };

    wase::system::Configuration config
    { 
        "Wase Engine", 1280, 720, true,
	scenes, "main"
    };
	
    wase::Engine::get().initialize(config);
    wase::Engine::get().run();
    wase::Engine::get().shutdown();
}
```
This would represent a project using the Wase Engine library and opening a window with the main scene.

**Comment by Crawfish-h** [comment]
I understand now and I have gotten wase-engine working again, thanks!
