### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by JelleVos1** [Wase-Engine/wase-engine#51]
**Describe the solution you'd like**
An UI component for a button.

**Additional context**
For this the Label component can be used.

**Comment by requizm** [comment]
I can add this but what exactly is the difference between Button and BoxCollider2D component?

The current BoxCollider2D component does not have a collision feature with other colliders. It only interacts with the mouse. For this reason, I did not find any significant difference between them, other than appearance.

To make the question a little clearer, what exactly do we expect from a button? Different types of buttons? (color_button, image_button, text_button, circle_collider etc.)

**Comment by JelleVos1** [comment]
> 
> 
> I can add this but what exactly is the difference between Button and BoxCollider2D component?
> 
> The current BoxCollider2D component does not have a collision feature with other colliders. It only interacts with the mouse. For this reason, I did not find any significant difference between them, other than appearance.
> 
> To make the question a little clearer, what exactly do we expect from a button? Different types of buttons? (color_button, image_button, text_button, circle_collider etc.)

I was thinking about a Button component to prevent people having to make an entity with a BoxCollider2D and a Label. The Button component should combine these 2 components and give more options like text alignment, button press effect(color changes a bit) and text color. The [Draw](https://github.com/Wase-Engine/wase-engine/blob/master/src/wase/core/draw.h) class could be used too for this to draw the button area, or like you say maybe a image_button where people can enter a custom image.

It doesn't have to be this advanced from the start but the very basic functionality shpuld just be a Label + BoxCollider2D + a rectangle drawn(with an image or the [Draw](https://github.com/Wase-Engine/wase-engine/blob/master/src/wase/core/draw.h) class)

**Comment by requizm** [comment]
As you mentioned I started doing something that includes Label + BoxCollider2D + a Rectangle properties.

**Comment by JelleVos1** [comment]
> 
> 
> As you mentioned I started doing something that includes Label + BoxCollider2D + a Rectangle properties.

Great, good luck! I assigned you to the issue. If you have any other questions feel free to ask.
