### ISSUE TITLE
x86 and x64 build support

### ISSUE THREAD

**Issue by requizm** [Wase-Engine/wase-engine#60]
**Is your feature request related to a problem? Please describe.**
I'm using MinGW-64 on Windows. Since my working environment is vscode, i can't build with that command: 
`cmake .. -G "MinGW Makefiles"`
<details>
  <summary>Error:</summary>

```
mingw makefiles does not support platform specification win32
```
</details>

**Describe the solution you'd like**
We can remove that line:
```
set(CMAKE_GENERATOR_PLATFORM win32)
```
Also, why only x86 build support?

**Comment by JelleVos1** [comment]
I started making the engine for x86 because every 64 system can run x86. But I think only the cmakelists has to be edited to make it possible to build for 64

**Comment by requizm** [comment]
> I started making the engine for x86 because every 64 system can run x86. But I think only the cmakelists has to be edited to make it possible to build for 64

Isn't it better if we give the choice to the person who will use the game engine? Btw x64 build working without any problems.
