### ISSUE TITLE
Continuous Integration tools

### ISSUE THREAD

**Issue by requizm** [Wase-Engine/wase-engine#64]
**Is your feature request related to a problem? Please describe.**
We should add it to see if there are errors in pull requests.

**Describe the solution you'd like**
We can use github actions, travis-ci etc.
Currently the following can be done on windows:
- MinGW 8.1.0 or up
- MSVC 2019

**Comment by JelleVos1** [comment]
Good idea, we can combine the tests to it too when we have those.
